name: Build B1 Pro (US)

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker.io/zmkfirmware/zmk-build-arm:3.2
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache west modules
        uses: actions/cache@v4
        continue-on-error: true
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
          key: $ runner.os -build-$ env.cache-name 

      - name: West init
        run: west init -l app

      - name: West update
        run: west update

      - name: Zephyr export
        run: west zephyr-export

      - name: Build firmware
        run: cd app && west build -p -b keychron -- -DSHIELD=keychron_b1_us

      - name: Upload firmware (.uf2)
        uses: actions/upload-artifact@v4
        with:
          name: keychron_b1_us-firmware
          path: app/build/zephyr/zmk.uf2
